version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: debug
    ports:
      - 5432:5432
  web:
    environment:
      - DJANGO_SECRET_KEY=awdawdwd
      - DJANGO_DEBUG=True
      - DJANGO_CONFIGURATION=Local
      - DJANGO_ADMIN_URL="admin/"
      - DATABASE_URL=postgres://postgres:debug@postgres:5432/postgres
    build: ./
    command: ./start.sh
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
