site_name: spotify_api
site_description: This is the test SpotifyAPI.
repo_url: https://github.com/kazimovzaman2/SpotifyAPI
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kazimovzaman2">kazimovzaman2</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
